apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks
  region: ap-south-1

nodeGroups:
   - name: node1
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: keypair
   - name: node2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: keypair
  